// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using music_chat.Models;

#nullable disable

namespace music_chat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.3.22175.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("music_chat.Models.DTO.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dbdef4c-271b-4515-8c5f-f56a18def458"),
                            ImageUrl = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("b885d1e4-0d07-44c0-b3bb-b36e85a6ab2c"),
                            ImageUrl = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user2.JPG",
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("da37ddc1-2f8e-44a6-a499-44227e2c48d6"),
                            ImageUrl = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user3.JPG",
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("music_chat.Models.DTO.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Email", "AccountId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Email = "user1@email.com",
                            AccountId = new Guid("5dbdef4c-271b-4515-8c5f-f56a18def458"),
                            Password = "user1"
                        },
                        new
                        {
                            Email = "user2@email.com",
                            AccountId = new Guid("b885d1e4-0d07-44c0-b3bb-b36e85a6ab2c"),
                            Password = "user2"
                        },
                        new
                        {
                            Email = "user3@email.com",
                            AccountId = new Guid("da37ddc1-2f8e-44a6-a499-44227e2c48d6"),
                            Password = "user3"
                        });
                });

            modelBuilder.Entity("music_chat.Models.DTO.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AuthorProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 1",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "2",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 2",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "3",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 3",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 12, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "4",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 4",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "5",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 5",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "6",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 6",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "7",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 7",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 16, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "8",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 8",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 17, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "9",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 9",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "10",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 10",
                            date = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 1, 2, 12, 19, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "11",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 11",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "12",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 12",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "13",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 13",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 12, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "14",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 14",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "15",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 15",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "16",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 16",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "17",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 17",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 16, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "18",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 18",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 17, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "19",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 19",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "20",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 20",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 19, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "21",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 21",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 20, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "22",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 22",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 21, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "23",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 23",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 22, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "24",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 24",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 23, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "25",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 25",
                            date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 2, 2, 12, 24, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "26",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 26",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "27",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 27",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "28",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 28",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 12, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "29",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 29",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "30",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 30",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "31",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 31",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "32",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 32",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 16, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "33",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 33",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 17, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "34",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 34",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "35",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 35",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 19, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "36",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 36",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 20, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "37",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 37",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 21, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "38",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 38",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 22, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "39",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 39",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 23, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "40",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 40",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 24, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "41",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 41",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 25, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "42",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 42",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 26, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "43",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 43",
                            date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 3, 2, 12, 27, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "44",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 44",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "45",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 45",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "46",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 46",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 12, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "47",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 47",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "48",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 48",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "49",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 49",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "50",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 50",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 16, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "51",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 51",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 17, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "52",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 52",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "53",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 53",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 19, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "54",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 54",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 20, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "55",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 55",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 21, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "56",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 56",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 22, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "57",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 57",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 23, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "58",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 58",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 24, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "59",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 59",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 25, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "60",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 60",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 26, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "61",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 61",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 27, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "62",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 62",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 28, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "63",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 63",
                            date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 4, 2, 12, 29, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "64",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 64",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "65",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 65",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "66",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 66",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 12, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "67",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 67",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "68",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 68",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "69",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 69",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "70",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 70",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 16, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "71",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 71",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 17, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "72",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 72",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "73",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 73",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 19, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "74",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 74",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 20, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "75",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 75",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 21, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "76",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 76",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 22, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "77",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 77",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 23, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "78",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 78",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 24, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "79",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 79",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 25, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "80",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 80",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 26, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "81",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 81",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 27, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "82",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 82",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 28, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "83",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 83",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 29, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "84",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 84",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 30, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "85",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 85",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 31, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "86",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 86",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 32, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "87",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 87",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 33, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "88",
                            AuthorProfileImage = "https://myapp-a3-cloud.s3.ap-southeast-2.amazonaws.com/user1.JPG",
                            AuthorUsername = "user1",
                            Content = "Test Message 88",
                            date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            timestamp = new DateTime(2022, 5, 5, 2, 12, 34, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
